// 20 Corporate Luxury & Photography Themes Definition & Theme Engine
export interface DashboardTheme {
  id: string;
  name: string;
  designStyle: string;
  mainFeel: string;
  bgPrimary: string;
  bgSurface: string;
  bgSurface2: string;
  borderSubtle: string;
  accentColor: string;
  accentText: string;
  textPrimary: string;
  textMuted: string;
  fontFamily: "font-serif" | "font-sans" | "font-mono";
  badgeBg: string;
  badgeText: string;
}

export const DASHBOARD_THEMES: DashboardTheme[] = [
  {
    id: "white-blue-editorial",
    name: "White & Royal Blue Executive",
    designStyle: "Clean White & Royal Sapphire Blue",
    mainFeel: "Executive, Professional & High-Contrast",
    bgPrimary: "#F8FAFC",
    bgSurface: "#FFFFFF",
    bgSurface2: "#F1F5F9",
    borderSubtle: "#E2E8F0",
    accentColor: "#2563EB",
    accentText: "#1D4ED8",
    textPrimary: "#0F172A",
    textMuted: "#64748B",
    fontFamily: "font-serif",
    badgeBg: "#DBEAFE",
    badgeText: "#1E40AF",
  },
  {
    id: "white-blue-seo",
    name: "White & Sky Blue Growth",
    designStyle: "Minimalist White & Azure Sky Blue",
    mainFeel: "Bright, Crisp & Data-Driven",
    bgPrimary: "#F1F5F9",
    bgSurface: "#FFFFFF",
    bgSurface2: "#E2E8F0",
    borderSubtle: "#CBD5E1",
    accentColor: "#0284C7",
    accentText: "#0369A1",
    textPrimary: "#0C4A6E",
    textMuted: "#475569",
    fontFamily: "font-sans",
    badgeBg: "#E0F2FE",
    badgeText: "#0369A1",
  },
  {
    id: "luxury-editorial",
    name: "Editorial Luxury (Warm Olive)",
    designStyle: "High-fashion Editorial & Warm Olive",
    mainFeel: "Premium, Sophisticated & Timeless",
    bgPrimary: "#111213",
    bgSurface: "#18191B",
    bgSurface2: "#212226",
    borderSubtle: "#2E302B",
    accentColor: "#5A5E4E",
    accentText: "#00D59B",
    textPrimary: "#FCF9F8",
    textMuted: "#A1A29A",
    fontFamily: "font-serif",
    badgeBg: "#00D59B",
    badgeText: "#09090B",
  },
  {
    id: "royal-heritage",
    name: "Royal Heritage",
    designStyle: "Traditional Indian luxury",
    mainFeel: "Grand & timeless",
    bgPrimary: "#12090C",
    bgSurface: "#1D1016",
    bgSurface2: "#2A1820",
    borderSubtle: "#3D222E",
    accentColor: "#E5C158",
    accentText: "#FDE68A",
    textPrimary: "#FAF4E8",
    textMuted: "#B8A5B0",
    fontFamily: "font-serif",
    badgeBg: "#E5C15825",
    badgeText: "#FDE68A",
  },
  {
    id: "elegant-minimal",
    name: "Elegant Minimal",
    designStyle: "Clean whitespace + serif",
    mainFeel: "Simple & premium",
    bgPrimary: "#090909",
    bgSurface: "#141414",
    bgSurface2: "#1E1E1E",
    borderSubtle: "#2E2E2E",
    accentColor: "#E2E8F0",
    accentText: "#FFFFFF",
    textPrimary: "#FFFFFF",
    textMuted: "#A1A1AA",
    fontFamily: "font-sans",
    badgeBg: "#E2E8F020",
    badgeText: "#FFFFFF",
  },
  {
    id: "cinematic-romance",
    name: "Cinematic Romance",
    designStyle: "Film-inspired photography",
    mainFeel: "Emotional & dramatic",
    bgPrimary: "#0D0F12",
    bgSurface: "#161A20",
    bgSurface2: "#202630",
    borderSubtle: "#2E3644",
    accentColor: "#F59E0B",
    accentText: "#FCD34D",
    textPrimary: "#F1F5F9",
    textMuted: "#94A3B8",
    fontFamily: "font-serif",
    badgeBg: "#F59E0B20",
    badgeText: "#FCD34D",
  },
  {
    id: "modern-luxury",
    name: "Modern Luxury",
    designStyle: "Contemporary + gold accents",
    mainFeel: "High-end & polished",
    bgPrimary: "#0E0E10",
    bgSurface: "#17171A",
    bgSurface2: "#1F1F23",
    borderSubtle: "#2A2A2E",
    accentColor: "#C89B3C",
    accentText: "#E8C978",
    textPrimary: "#F5F5F2",
    textMuted: "#9A9A9E",
    fontFamily: "font-serif",
    badgeBg: "#C89B3C20",
    badgeText: "#E8C978",
  },
  {
    id: "classic-ivory",
    name: "Classic Ivory",
    designStyle: "Ivory, beige & brown",
    mainFeel: "Soft & elegant",
    bgPrimary: "#161311",
    bgSurface: "#221E1A",
    bgSurface2: "#2E2A24",
    borderSubtle: "#403A32",
    accentColor: "#F5EBE0",
    accentText: "#FAF4ED",
    textPrimary: "#F5EBE0",
    textMuted: "#C2B4A3",
    fontFamily: "font-serif",
    badgeBg: "#F5EBE020",
    badgeText: "#F5EBE0",
  },
  {
    id: "royal-gold",
    name: "Royal Gold",
    designStyle: "Black, gold & cream",
    mainFeel: "Rich & luxurious",
    bgPrimary: "#000000",
    bgSurface: "#111111",
    bgSurface2: "#1C1C1C",
    borderSubtle: "#333333",
    accentColor: "#FFD700",
    accentText: "#FFE55C",
    textPrimary: "#FFF8DC",
    textMuted: "#B8B59E",
    fontFamily: "font-serif",
    badgeBg: "#FFD70025",
    badgeText: "#FFD700",
  },
  {
    id: "rose-romance",
    name: "Rose Romance",
    designStyle: "White, blush & rose",
    mainFeel: "Romantic & feminine",
    bgPrimary: "#140C10",
    bgSurface: "#20141A",
    bgSurface2: "#2E1D26",
    borderSubtle: "#422B37",
    accentColor: "#E8A5B8",
    accentText: "#FCE7F3",
    textPrimary: "#FFF0F5",
    textMuted: "#C49BB0",
    fontFamily: "font-serif",
    badgeBg: "#E8A5B820",
    badgeText: "#FCE7F3",
  },
  {
    id: "timeless-wedding",
    name: "Timeless Wedding",
    designStyle: "Classic typography",
    mainFeel: "Traditional & elegant",
    bgPrimary: "#0F0E0E",
    bgSurface: "#1B1918",
    bgSurface2: "#272422",
    borderSubtle: "#3B3734",
    accentColor: "#D4AF37",
    accentText: "#F3E3A1",
    textPrimary: "#FAF0E6",
    textMuted: "#B3A69A",
    fontFamily: "font-serif",
    badgeBg: "#D4AF3720",
    badgeText: "#F3E3A1",
  },
  {
    id: "magazine-vogue",
    name: "Magazine Vogue",
    designStyle: "Fashion magazine layout",
    mainFeel: "Editorial & stylish",
    bgPrimary: "#050505",
    bgSurface: "#121212",
    bgSurface2: "#1C1C1C",
    borderSubtle: "#2C2C2C",
    accentColor: "#E11D48",
    accentText: "#FDA4AF",
    textPrimary: "#FFFFFF",
    textMuted: "#A1A1AA",
    fontFamily: "font-sans",
    badgeBg: "#E11D4820",
    badgeText: "#FDA4AF",
  },
  {
    id: "artisan-heritage",
    name: "Artisan Heritage",
    designStyle: "Indian traditional motifs",
    mainFeel: "Cultural & artistic",
    bgPrimary: "#160B08",
    bgSurface: "#24140F",
    bgSurface2: "#331D16",
    borderSubtle: "#4A2B21",
    accentColor: "#E07A5F",
    accentText: "#F4A261",
    textPrimary: "#F7F1E5",
    textMuted: "#C7B299",
    fontFamily: "font-serif",
    badgeBg: "#E07A5F20",
    badgeText: "#F4A261",
  },
  {
    id: "dark-cinematic",
    name: "Dark Cinematic",
    designStyle: "Black + warm gold",
    mainFeel: "Dramatic & premium",
    bgPrimary: "#08080A",
    bgSurface: "#121218",
    bgSurface2: "#1A1A24",
    borderSubtle: "#2A2A38",
    accentColor: "#F59E0B",
    accentText: "#FCD34D",
    textPrimary: "#F8FAFC",
    textMuted: "#94A3B8",
    fontFamily: "font-serif",
    badgeBg: "#F59E0B25",
    badgeText: "#FCD34D",
  },
  {
    id: "soft-luxury",
    name: "Soft Luxury",
    designStyle: "Cream + champagne",
    mainFeel: "Calm & sophisticated",
    bgPrimary: "#131316",
    bgSurface: "#1C1C22",
    bgSurface2: "#272730",
    borderSubtle: "#393944",
    accentColor: "#E6C594",
    accentText: "#F3E9DC",
    textPrimary: "#F3E9DC",
    textMuted: "#BDB0A4",
    fontFamily: "font-serif",
    badgeBg: "#E6C59420",
    badgeText: "#F3E9DC",
  },
  {
    id: "contemporary-indian",
    name: "Contemporary Indian",
    designStyle: "Modern + cultural elements",
    mainFeel: "Modern & rooted",
    bgPrimary: "#0B131F",
    bgSurface: "#142132",
    bgSurface2: "#1E2F46",
    borderSubtle: "#2C4362",
    accentColor: "#38BDF8",
    accentText: "#BAE6FD",
    textPrimary: "#E0F2FE",
    textMuted: "#94A3B8",
    fontFamily: "font-sans",
    badgeBg: "#38BDF820",
    badgeText: "#BAE6FD",
  },
  {
    id: "destination-romance",
    name: "Destination Romance",
    designStyle: "Travel/wedding editorial",
    mainFeel: "Dreamy & cinematic",
    bgPrimary: "#120E16",
    bgSurface: "#1D1724",
    bgSurface2: "#2A2234",
    borderSubtle: "#3E324D",
    accentColor: "#F43F5E",
    accentText: "#FECDD3",
    textPrimary: "#F5F3FF",
    textMuted: "#B8A9C9",
    fontFamily: "font-serif",
    badgeBg: "#F43F5E20",
    badgeText: "#FECDD3",
  },
  {
    id: "film-grain",
    name: "Film & Grain",
    designStyle: "Analog photography aesthetic",
    mainFeel: "Nostalgic & artistic",
    bgPrimary: "#151515",
    bgSurface: "#222222",
    bgSurface2: "#2E2E2E",
    borderSubtle: "#404040",
    accentColor: "#D97706",
    accentText: "#FBBF24",
    textPrimary: "#F3EFE0",
    textMuted: "#A39E93",
    fontFamily: "font-mono",
    badgeBg: "#D9770620",
    badgeText: "#FBBF24",
  },
  {
    id: "monochrome-luxe",
    name: "Monochrome Luxe",
    designStyle: "Black, white & grey",
    mainFeel: "Minimal & powerful",
    bgPrimary: "#000000",
    bgSurface: "#141414",
    bgSurface2: "#222222",
    borderSubtle: "#333333",
    accentColor: "#E2E8F0",
    accentText: "#FFFFFF",
    textPrimary: "#FFFFFF",
    textMuted: "#A1A1AA",
    fontFamily: "font-mono",
    badgeBg: "#E2E8F020",
    badgeText: "#FFFFFF",
  },
  {
    id: "champagne-elegance",
    name: "Champagne Elegance",
    designStyle: "Champagne + ivory",
    mainFeel: "Premium & warm",
    bgPrimary: "#15120E",
    bgSurface: "#221C16",
    bgSurface2: "#302820",
    borderSubtle: "#453B30",
    accentColor: "#F3E3A1",
    accentText: "#FFF3C4",
    textPrimary: "#FAF4E8",
    textMuted: "#C7B9A5",
    fontFamily: "font-serif",
    badgeBg: "#F3E3A120",
    badgeText: "#F3E3A1",
  },
  {
    id: "garden-romance",
    name: "Garden Romance",
    designStyle: "Botanical + pastel",
    mainFeel: "Natural & romantic",
    bgPrimary: "#091410",
    bgSurface: "#11221C",
    bgSurface2: "#1B332B",
    borderSubtle: "#284A3F",
    accentColor: "#84CC16",
    accentText: "#D9F99D",
    textPrimary: "#ECFDF5",
    textMuted: "#94A3B8",
    fontFamily: "font-serif",
    badgeBg: "#84CC1620",
    badgeText: "#D9F99D",
  },
  {
    id: "heirloom-wedding",
    name: "Heirloom Wedding",
    designStyle: "Vintage + heritage",
    mainFeel: "Classic & sentimental",
    bgPrimary: "#140F0D",
    bgSurface: "#221915",
    bgSurface2: "#30241E",
    borderSubtle: "#46352D",
    accentColor: "#D97706",
    accentText: "#FDE68A",
    textPrimary: "#FFFBEB",
    textMuted: "#C2AF9E",
    fontFamily: "font-serif",
    badgeBg: "#D9770620",
    badgeText: "#FDE68A",
  },
];

export function getThemeById(id: string): DashboardTheme {
  return DASHBOARD_THEMES.find((t) => t.id === id) || DASHBOARD_THEMES[0]; // Default to Editorial Luxury (Design Brief)
}
