import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          teal: "#00d59b",
          mint: "#10e7a8",
          accent: "#06d6a0",
        },
        "on-secondary-fixed": "#341100",
        "on-secondary": "#ffffff",
        background: "#fcf9f8",
        "on-surface-variant": "#464740",
        "on-surface": "#1b1c1c",
        "tertiary-fixed": "#fcddc2",
        "surface-variant": "#e5e2e1",
        "primary-fixed-dim": "#c6c8b5",
        "on-secondary-container": "#773a16",
        "surface-container-high": "#eae7e7",
        "surface-tint": "#5d6050",
        "surface-bright": "#fcf9f8",
        surface: "#fcf9f8",
        "secondary-fixed-dim": "#ffb691",
        "surface-dim": "#dcd9d9",
        "tertiary-container": "#89705a",
        "inverse-on-surface": "#f3f0ef",
        "outline-variant": "#c7c7bd",
        "on-tertiary-container": "#fffbff",
        "primary-container": "#737665",
        "on-error": "#ffffff",
        "surface-container": "#f0eded",
        "secondary-fixed": "#ffdbcb",
        "on-primary": "#ffffff",
        secondary: "#8f4d27",
        "surface-container-low": "#f6f3f2",
        "inverse-surface": "#303030",
        "secondary-container": "#fda77a",
        tertiary: "#6e5843",
        "on-primary-fixed-variant": "#454839",
        "on-tertiary-fixed": "#281808",
        "on-background": "#1b1c1c",
        "surface-container-highest": "#e5e2e1",
        "on-secondary-fixed-variant": "#723612",
        "on-tertiary-fixed-variant": "#57432f",
        error: "#ba1a1a",
        "on-primary-container": "#fcfee9",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        outline: "#77786f",
        "on-primary-fixed": "#1a1d10",
        "on-error-container": "#93000a",
        "primary-fixed": "#e2e4d0",
        primary: "#5a5e4e",
        "inverse-primary": "#c6c8b5",
        "tertiary-fixed-dim": "#dfc1a7",
      },
      boxShadow: {
        ambient: "0 30px 60px -15px rgba(0, 0, 0, 0.35), 0 10px 25px -5px rgba(0, 0, 0, 0.2)",
        spotlight: "0 35px 70px -15px rgba(0, 0, 0, 0.45), 0 0 45px -5px rgba(16, 231, 168, 0.3)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xs": "0.375rem",
        "space-sm": "0.75rem",
        "margin-mobile": "1.5rem",
        margin: "4rem",
        "space-lg": "2rem",
        "section-gap-mobile": "4.5rem",
        "space-xl": "3.5rem",
        "space-md": "1.25rem",
        "gutter-mobile": "1rem",
        "section-gap": "7.5rem",
        gutter: "2rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        serif: ["Playfair Display", "serif"],
        display: ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "display-md": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "display-md-mobile": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        script: ["Great Vibes", "cursive"],
        dancing: ["Dancing Script", "cursive"],
      },
      fontSize: {
        "display-lg": ["4.5rem", { lineHeight: "5rem", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-md": ["3.5rem", { lineHeight: "4rem", letterSpacing: "-0.015em", fontWeight: "400" }],
        "headline-lg-mobile": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "0em", fontWeight: "500" }],
        "headline-lg": ["2.5rem", { lineHeight: "3rem", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.08em", fontWeight: "500" }],
        "body-sm": ["0.875rem", { lineHeight: "1.4rem", fontWeight: "400" }],
        "headline-sm": ["1.5rem", { lineHeight: "2rem", fontWeight: "500" }],
        "display-md-mobile": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["1rem", { lineHeight: "1.65rem", fontWeight: "300" }],
        "body-lg": ["1.125rem", { lineHeight: "1.875rem", letterSpacing: "0.01em", fontWeight: "300" }],
        "display-lg-mobile": ["2.75rem", { lineHeight: "3.25rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "title-lg": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.12em", fontWeight: "500" }],
        "headline-md": ["2rem", { lineHeight: "2.5rem", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
